remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-remote-theme

title: KIOPTRIX LEVEL 1
description: Kioptrix Level 1 Penetration Testing Walkthrough — Boot to Root.
baseurl: "/Kioptrix-Level-1-Walkthrough"

style: dark
