theme: jekyll-theme-tactile
title: "KIOPTRIX LEVEL 1"
description: "Kioptrix Level 1 Penetration Testing Walkthrough — Boot to Root"
show_downloads: false
baseurl: "/Kioptrix-Level-1-Walkthrough"
url: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  name: itstallam
  url: https://github.com/itstallam
